### ISSUE TITLE
Paths don't result in the robot driving the correct distances

### ISSUE THREAD

**Issue by CierraO** [Team2168/2020_SwerveBot#44]

**Comment by jcorcoran** [comment]
I think we largely came through this. From what I recall we had to resolve:

- fix timestep in pathweaver
- fix inch->ft if ft->inch unit conversion in PathController for the min speed parameter (minimum speed was defined as 1ft/sec so any velocities for individual path segments less than this caused us to move faster than we were requesting, translating to longer distances traveled
- Adjust the accel, jerk, and velocity limits in pathweaver to be more aggressive so that we get out of our min speed zone more quickly
- adjust the gains for the velocity controller so they can more aggressively track the target setpoint

We are still off a bit from requested vs actual distances traveled... I think the remaining error could be removed by further refining the PID gains for the velocity controller, or more accurate measurement of wheel diameter. Our position achieved over any path traveled is very repeatable. It's something minor that's left.
